language: php
php:
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.6

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: LARAVEL_VERSION=5.6

before_script:
  - travis_retry composer self-update
  - if [ "$LARAVEL_VERSION" != "" ]; then composer create-project "laravel/laravel:${LARAVEL_VERSION}.*"; fi;
  - cd ./laravel
  - composer config repositories.mdaliyan vcs https://github.com/mdaliyan/farsi-request.git
  - composer require mdaliyan/farsi-request dev-master
  - sed -i "s/protected \$middleware = \[/protected \$middleware = \[\n\t\t\\\\Mdaliyan\\\\FarsiRequest\\\\Middleware\\\\ReplaceArabicCharacters::class,/" ./app/Http/Kernel.php
  - mkdir ./app/Http/Requests
  - mv ./vendor/mdaliyan/farsi-request/tests/${LARAVEL_VERSION}/web.php ./routes
  - mv ./vendor/mdaliyan/farsi-request/tests/${LARAVEL_VERSION}/TestRequest.php ./app/Http/Requests
  - mv ./vendor/mdaliyan/farsi-request/tests/${LARAVEL_VERSION}/FarsiRequestTest.php ./tests/Feature/

script:
  - phpunit