language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.4
  - LARAVEL_VERSION=5.5
  - LARAVEL_VERSION=5.6
  - LARAVEL_VERSION=5.7

directories:
  - $HOME/.composer/cache/files
  
cache:
  directories:
  - .autoconf
  - $HOME/.m2

matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION=5.5
    - php: 5.6
      env: LARAVEL_VERSION=5.6
    - php: 5.6
      env: LARAVEL_VERSION=5.7
    - php: 7.0
      env: LARAVEL_VERSION=5.6
    - php: 7.0
      env: LARAVEL_VERSION=5.7

before_script:
  - travis_retry composer self-update
  - if [ "$LARAVEL_VERSION" != "" ]; then composer create-project "laravel/laravel:${LARAVEL_VERSION}.*"; fi;
  - cd ./laravel
  - composer require mdaliyan/farsi-request dev-master
  - sed -i "s/protected \$middleware = \[/protected \$middleware = \[\n\t\t\\\\Mdaliyan\\\\FarsiRequest\\\\Middleware\\\\ReplaceArabicCharacters::class,/" ./app/Http/Kernel.php
  - mkdir ./app/Http/Requests
  - mv ./vendor/mdaliyan/farsi-request/tests/web.php ./routes
  - mv ./vendor/mdaliyan/farsi-request/tests/TestRequest.php ./app/Http/Requests
  - mv ./vendor/mdaliyan/farsi-request/tests/FarsiRequestTest.php ./tests/Feature/

script:
  - phpunit
